# 工作流的名称
name: CheckScores

# 工作流运行的名称
run-name: ${{ github.workflow }} ${{ github.sha }}

# 指定此工作流的触发器
on:
  schedule:
    - cron: "*/30 * * * *" # 每30分钟自动执行一次
  workflow_dispatch: # 可以手动执行
    inputs:
      force_push_message:
        description: "Whether or not to force a push message?"
        required: true
        default: "False"
        type: choice
        options:
          - "True"
          - "False"

jobs:
  CheckScores:
    name: CheckScores
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@main

      - name: Configure Git
        run: |
          git config --global user.email "actions@github.com"
          git config --global user.name "GitHub Actions"

      - name: Set up Go
        uses: actions/setup-go@main
        with:
          go-version: "1.25"
          cache: true

      - name: Build
        env:
          GOPROXY: "https://goproxy.cn,direct"
          GOTOOLCHAIN: "auto"
        run: |
          go build -ldflags="-s -w" -o zfcheckscores .

      - name: Test
        env:
          GOPROXY: "https://goproxy.cn,direct"
          GOTOOLCHAIN: "auto"
        run: |
          go test -v ./...

      - name: Get Connection
        run: |
          url="https://ifconfig.me/all"
          response=$(curl -s -X GET "$url")
          echo "$response"

      - name: Run main program
        id: run_main_program
        env:
          GOPROXY: "https://goproxy.cn,direct"
          FORCE_PUSH_MESSAGE: ${{ github.event.inputs.force_push_message }}
          GITHUB_ACTIONS: ${{github.actions}}
          URL: ${{ secrets.URL }}
          USERNAME: ${{ secrets.USERNAME }}
          PASSWORD: ${{ secrets.PASSWORD }}
          TOKEN: ${{ secrets.TOKEN }}
          COOKIES: ${{ secrets.COOKIES }}
          GITHUB_REF_NAME: ${{ github.ref_name }}
          GITHUB_EVENT_NAME: ${{ github.event_name }}
          GITHUB_ACTOR: ${{ github.actor }}
          GITHUB_ACTOR_ID: ${{ github.actor_id }}
          GITHUB_TRIGGERING_ACTOR: ${{ github.triggering_actor }}
          REPOSITORY_NAME: ${{ github.repository }}
          GITHUB_SHA: ${{ github.sha }}
          GITHUB_WORKFLOW: ${{ github.workflow }}
          GITHUB_RUN_NUMBER: ${{ github.run_number }}
          GITHUB_RUN_ID: ${{ github.run_id }}
        run: |
          # 判断环境变量是否为空
          if [ -z "$URL" ]; then
            echo "URL Secret is empty!"
            echo "::error title=URL Secret is empty!" \
            "::Your 'URL' Secret is not filled with any" \
            "information, so your program will not work!"
            Whether_Secret_is_empty=true
          fi
          if [ -z "$USERNAME" ] && [ -z "$COOKIES" ]; then
            echo "USERNAME and COOKIES Secret are both empty! At least one required."
            echo "::error title=Login credentials missing!" \
            "::Must provide either USERNAME+PASSWORD or COOKIES."
            Whether_Secret_is_empty=true
          fi
          if [ -z "$TOKEN" ]; then
            echo "TOKEN Secret is empty!"
            echo "::error title=TOKEN Secret is empty!" \
            "::Your 'TOKEN' Secret is not filled with any" \
            "information, so your program will not work!"
            Whether_Secret_is_empty=true
          fi
          if [ "$Whether_Secret_is_empty" = true ]; then
            echo "One or more Secrets are empty."
            exit 1
          fi

          if [ -z "${{ github.event.inputs.force_push_message }}" ]; then
            export FORCE_PUSH_MESSAGE="False"
          else
            export FORCE_PUSH_MESSAGE="${{ github.event.inputs.force_push_message }}"
          fi
          export BEIJING_TIME="$(TZ='Asia/Shanghai' date +'%Y-%m-%d %H:%M:%S:%3N')"
          echo "BEIJING_TIME=$BEIJING_TIME" >> $GITHUB_OUTPUT

          # 脱敏函数
          mask_middle() {
            local input=$1
            local length=${#input}
            if [ $length -le 3 ]; then
              echo $(printf '%*s' $length | tr ' ' '*')
            else
              local first=${input:0:1}
              local last=${input: -1}
              local middle_length=$((length - 2))
              local middle=$(printf '%*s' $middle_length | tr ' ' '*')
              echo "${first}${middle}${last}"
            fi
          }

          anonymize_domain() {
            local url=$1
            local protocol=$(echo "$url" | sed -n 's#^\(.*://\).*#\1#p')
            local rest=$(echo "${url#*://}")
            local domain=$(echo "$rest" | sed 's#/.*##')
            local path=$(echo "$rest" | sed 's#^[^/]*##')
            IFS='.' read -r -a domain_parts <<< "$domain"
            local anonymized_domain=""
            for part in "${domain_parts[@]}"; do
              anonymized_domain+=$(printf '%*s' ${#part} | tr ' ' '*'). 
            done
            anonymized_domain=${anonymized_domain%.}
            echo "${protocol}${anonymized_domain}${path}"
          }

          LOGINURL="xtgl/login_slogin.html"

          echo "Url: $(anonymize_domain "$URL")${LOGINURL}"
          echo "Username: $(mask_middle "$USERNAME")"
          echo "Force Push Message: $FORCE_PUSH_MESSAGE"
          echo "Branch Name: $GITHUB_REF_NAME"
          echo "Triggered By: $GITHUB_EVENT_NAME"
          echo "Initial Run By: $GITHUB_ACTOR"
          echo "Initial Run By ID: $GITHUB_ACTOR_ID"
          echo "Initiated Run By: $GITHUB_TRIGGERING_ACTOR"
          echo "Repository Name: $REPOSITORY_NAME"
          echo "Commit SHA: $GITHUB_SHA"
          echo "Workflow Name: $GITHUB_WORKFLOW"
          echo "Workflow Number: $GITHUB_RUN_NUMBER"
          echo "Workflow ID: $GITHUB_RUN_ID"
          echo "Beijing Time: $BEIJING_TIME"
          echo "Copyright © 2024 NianBroken. All rights reserved."
          echo "------"

          go run .

      - name: Force push changes to the running branch
        run: |
          git add .
          git commit -m "Update from GitHub Actions" || true
          git push origin $GITHUB_REF_NAME --force
